### PR TITLE
Elm 0.18 compatibility

### PR DESCRIPTION
**Pull request by spookylukey**
Fixes for Elm 0.18, plus updates for latest elm-test.

### CODE REVIEW

**Comment by vanwagonet** [comment]
I merged the elm-format commit. Could you rebase, and take a look at the .travis.yml?

I haven't done anything in elm for a long while, and am not sure what the best way to do CI is.

**Comment by spookylukey** [comment]
@vanwagonet I'll have a look, one of them is the code linter complaining it seems, I'm not sure about the other.

**Comment by spookylukey** [comment]
@vanwagonet OK, progress here.

We are now seeing failures only on 'stable' Node (v10.9.0), which is what I also get locally, while lts (v8.11.4) passes.

My guesses are regressions in Intl support in Node, or possibly these are real bugs in elm-intl that have been uncovered by better Intl support in Node, I don't have time to look into these at the moment.

**Comment by vanwagonet** [comment]
I think there are actual regressions in Node v10 Intl support. https://github.com/nodejs/node/issues/22156

I think this is good to merge.

**Comment by srl295** [comment]
@vanwagonet ^ regression fixed in https://github.com/nodejs/node/pull/23764

**Comment by vanwagonet** [comment]
Thanks @srl295!

**Pull request merged**
